# Site settings
title: "学术主页"
description: "个人学术研究主页"
author: "Your Name"
email: "your.email@domain.com"

# Site URL
url: "https://xianyu564.github.io"
baseurl: ""

# Theme
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Language settings for Chinese support
lang: zh-CN

# Permalink structure for blog posts
permalink: /blog/:title/

# Navigation
navigation:
  - title: "主页"
    url: /
  - title: "关于"
    url: /about/
  - title: "发表论文"
    url: /publications/
  - title: "项目"
    url: /projects/
  - title: "博客"
    url: /blog/

# Social media links
social:
  github: "xianyu564"
  google_scholar: "your-scholar-id"
  twitter: "your-twitter-handle"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Build settings
safe: false
incremental: false