# Site settings
title: "张子阳的学术主页"
description: "AI导航的计算生物医药与决策智能 - Zhang Ziyang's Academic Homepage"
author: "Zhang Ziyang"
email: "z_zz@u.nus.edu"

# Site URL
url: "https://xianyu564.github.io"
baseurl: ""

# Theme
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

# Language settings for Chinese support
lang: zh-CN

# Navigation
navigation:
  - title: "主页"
    url: /
  - title: "关于"
    url: /about/
  - title: "发表论文"
    url: /publications/
  - title: "项目"
    url: /projects/

# Social media links
social:
  github: "xianyu564"
  google_scholar: "your-scholar-id"
  twitter: "your-twitter-handle"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Build settings
safe: false
incremental: false