# Site settings
title: "李明辉 - 学术主页"
description: "人工智能与数据科学研究者，专注于机器学习、深度学习和计算机视觉"
author: "李明辉"
email: "lminghui@university.edu.cn"

# Site URL
url: "https://xianyu564.github.io"
baseurl: ""

# Theme
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Language settings for Chinese support
lang: zh-CN

# Permalink structure for blog posts
permalink: /blog/:title/

# Navigation
navigation:
  - title: "主页"
    url: /
  - title: "关于"
    url: /about/
  - title: "发表论文"
    url: /publications/
  - title: "项目"
    url: /projects/
  - title: "研究影响力"
    url: /research-metrics/
  - title: "博客"
    url: /blog/

# Social media links
social:
  github: "xianyu564"
  google_scholar: "ABC123DEF456"
  orcid: "0000-0000-0000-0000"
  researchgate: "Li-Minghui-12345"
  linkedin: "li-minghui-phd"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Build settings
safe: false
incremental: false